name: Gradle Publish

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Import GPG keys
        run: ./import_gpg.sh
        shell: bash
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Publish With Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish -Psigning.keyId="$GPG_KEY_ID" -Psigning.password="$GPG_PASSWORD" -Psigning.secretKeyRingFile="~/secring.gpg"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
      - name: Close and release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: closeAndReleaseRepository