raftexample1:./build/raft -conf config/one.json 
raftexample2:./build/raft -conf config/two.json 
raftexample3:./build/raft -conf config/three.json 
raftexample4:./build/raft -conf config/four.json 
raftexample5:./build/raft -conf config/five.json 