proxy-app = "kvstore"
log-level = "debug"
mode = "validator"

[rpc]
laddr = "tcp://0.0.0.0:26657"
pprof-laddr = ":6060"

[instrumentation]
prometheus = false

[consensus]
create-empty-blocks = false
timeout-propose = "3s"
timeout-prevote = "3s"
timeout-precommit = "3s"

[p2p]
netrix-addr = "127.0.0.1:7074"
netrix-client-addr = "0.0.0.0:8080"
pex = false